import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header";
import Footer from "../components/footer";
// import { getCookie } from "cookies-next";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cobbleweb Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const isAuth = getCookie("token");
  // if(isAuth) {

  // }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container max-w-screen-xl min-h-screen p-6 mx-auto md:flex-row">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
